[ECO-418] Added table model.
mobbexco/php-plugins-sdk pull request #12
Opened 2023-07-17 20:21 UTC by EMunozMobbex

2023-08-25 22:44 UTC, jlmobbex requested changes

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +        foreach ($this->definition as $format) {
Más que `$format`, yo lo llamaría `$column`, o `$columnFormat`

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +        $this->definition = empty($definition) ? self::getTableDefinition($name) : $definition;
La principal utilidad de empty o isset (su contraparte) es detectar también si una variable o posición no está definida, en este caso `$definition` siempre va a estar definido porque está puesto como param, por lo que se puede usar simplemente un:
```php
$this->definition = $definition ?: self::getTableDefinition($name);
```

2023-08-25 22:44 UTC, jlmobbex commented on src/utils/table-definition/transaction.php
> + */
Hay alguna doc que se pueda dejar acá con un `@see` para entender de donde viene el formato? Si esto se agrega estaría bueno agregarlo en todas las definiciones.

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +     * @param string $name Table name.
Este punto queda un poco lejos del código del método, en general se suele dejar un comentario que dice `Constructor` arriba del todo en el bloque de documentación para no perder de que método se trata. También se suele dejar la información de para que sirve la clase, pero eso es más opcional, ya que también se puede dejar arriba de todo.

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +        $this->init();
`init` hace lo invitable jeje. Por lo que yo recomendaría que se unifique con el construct, ya que no se ejecuta en ningún otro lugar y tiene su misma funcionalidad (según el nombre init y construct serían lo mismo).

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +                . (!empty($format['Default']) ? 'DEFAULT ' . $format['Default'] : '')
Vi que default está definido en todos los archivos definitions, es obligatorio? Si es así no haría falta validar con empty:
```php
. ($format['Default'] ? 'DEFAULT ' . $format['Default'] : '')
```

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +        //Add columns
Recordá separar los bloques de código con una línea vacía

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +            return true;
Esto solo chequea que existan las columnas, podría modificarse la definición de una de ellas y retornaría `true` de todas formas. Ej. se elimina un extra `auto_incremental` de una columna.

2023-08-25 22:44 UTC, jlmobbex commented on src/Model/Table.php
> +        return true;
Este método busca que columnas están en un array y no en el otro, se podría resumir en dos array_diff_key. Dejo ejemplos usando funciones de array para encontrar diferencias y columnas en común:
```php
$commonColumns     = array_intersect_key($columns, $this->definition);
$deprecatedColumns = array_diff_key($columns, $this->definition);
$missingColumns    = array_diff_key($this->definition, $columns);
```

De todas formas, no estoy seguro que esta sea la forma correcta de realizar el chequeo, se debería chequear sea exactamente igual a la que está en definition. Y si hay deprecadas eliminarlas en vez de emitir un warning.

2023-08-28 18:57 UTC, EMunozMobbex commented on src/Model/Table.php
> +            foreach ($this->definition as $column) {
Necesito el foreach porque definition es un array indexado, entonces no tengo forma de saber en que posición podría estar la columna que tiene el primary key, dejo la definicion de log de ejemplo

```php
    /**
 * Mobbex Log table definition. 
 */
return [
    ['Field' => 'log_id',        'Type' => 'int(11)',  'Null' => 'NO', 'Key' => 'PRI', 'Default' => null, 'Extra' => 'auto_increment'],
    ['Field' => 'type',          'Type' => 'text',     'Null' => 'NO', 'Key' => '',    'Default' => null, 'Extra' => ''],
    ['Field' => 'message',       'Type' => 'text',     'Null' => 'NO', 'Key' => '',    'Default' => null, 'Extra' => ''],
    ['Field' => 'data',          'Type' => 'text',     'Null' => 'NO', 'Key' => '',    'Default' => null, 'Extra' => ''],
    ['Field' => 'creation_date', 'Type' => 'datetime', 'Null' => 'NO', 'Key' => '',    'Default' => null, 'Extra' => ''],
];
```

2023-08-28 19:36 UTC, EMunozMobbex commented on src/Model/Table.php
> +            return true;
El método chequea la definición comparando que el array de definición sea exactamente igual que lo que retorna como definicion "show columns", en esta linea:

```php
            //Check column definition
        foreach ($this->definition as $column)
            if(!in_array($column, $columns))
                return false;
```

Por esta razón me aseguré de que las definiciones fueran compatibles con el retorno de show columns, para pdoer comparar que ambos array fueran exactamente iguales asegurando que la definición sea la correcta :) en el caso que comentas, de modificarse el auto_increment ambos array presentarian una diferencia y retornaria false

2023-08-28 19:46 UTC, EMunozMobbex commented on src/Model/Table.php
> +        return true;
Como definition y columns son arrays de arrays, al hacer la comparación no solo comprueba que la columna exista si no, que el array de definición de la columna sea igual, por tanto en caso de haber diferencias en la definición retorna false, ya que no se esta revisando si existe la columna en la lista de columnas, se esta revisando si existe un array igual en contenido al de definition en la lista de columnas, para poder hacer esta comprobación es que segui el formato de retorno de show columns!

dejo acá una muestra donde se puede corroborar:
https://3v4l.org/FhdZB

2023-08-28 19:47 UTC, EMunozMobbex commented on src/Model/Table.php
> +        return true;
En el caso de las columnas deprecadas lo deje momentáneamente hasta evaluar, por si hubiese información que migrar en alguna

2023-08-31 17:05 UTC, jlmobbex requested changes

2023-09-11 16:24 UTC, jlmobbex requested changes

2023-09-11 16:24 UTC, jlmobbex commented on src/Model/Db.php
> +        $this->prefix = $prefix;
Definir las propiedades dinámicamente arroja un error a partir de PHP 8. Si se establece en este construct debería estar definida en esta clase y no en las hijas (capaz se malinterpretó este comentario https://github.com/mobbexco/php-plugins-sdk/pull/12#discussion_r1276486045)

2023-09-11 17:25 UTC, EMunozMobbex commented on src/Model/Db.php
> +        $this->prefix = $prefix;
Si, entendí mal el comentario, me parecía que lo que me estabas pidiendo era medio extraño, lo hablamos bien en daily

2023-09-11 20:57 UTC, jlmobbex approved these changes

2023-09-11 20:57 UTC, merged