[ECO-419] Add cache model
mobbexco/php-plugins-sdk pull request #13
Opened 2023-07-18 20:50 UTC by mobbexLuis

2023-07-19 14:08 UTC, EMunozMobbex commented on src/Model/Cache.php
> +        return isset($key) && isset($data) ? true : null;
Este método debería estar vacio y retornar siempre null pase lo que pase.

2023-07-19 14:09 UTC, EMunozMobbex commented on src/Model/Cache.php
> +        return isset($key) ? true : null;
Igual que en el caso anterior este método debería estar vacio y retornar siempre null pase lo que pase.

algo asi como public function get($key){}

2023-07-19 14:20 UTC, EMunozMobbex commented on src/Platform.php
> +        $cache ? self::$cache = $cache : self::$cache = new \Mobbex\Model\Cache;
quiza queda mejor 
self::$cache = $cache ? $cache : new \Mobbex\Cache();

2023-07-19 19:06 UTC, EMunozMobbex approved these changes

2023-08-10 21:34 UTC, jlmobbex requested changes

2023-08-10 21:34 UTC, jlmobbex commented on src/Platform.php
>      public static function loadModels($cache)
Tendría que ser opcional el parámetro, para que cuando se agreguen más modelos sólo se agregue el que se quiere agregar.

2023-08-14 19:42 UTC, jlmobbex approved these changes

2023-08-14 19:42 UTC, merged