Update subscription and subscriber modules
mobbexco/php-plugins-sdk pull request #22
Opened 2023-11-06 18:37 UTC by mobbexLuis

add necessary configurations for woocommerce subscriptions
add position addresses to subscriber model

2023-11-08 17:33 UTC, EMunozMobbex requested changes

2023-11-08 17:33 UTC, EMunozMobbex commented on src/Modules/Subscription.php
> +                'test'        => $test,
El test no debería tomarlo de `$this->settings['test']` en lugar de pasarlo como parámetro?

2023-11-13 12:05 UTC, EMunozMobbex approved these changes

2023-11-16 18:57 UTC, EMunozMobbex approved these changes

2024-01-19 05:20 UTC, jlmobbex requested changes

2024-01-19 05:20 UTC, jlmobbex commented on tests/SubscriptionTest.php
> +            true
Acá quedó el parámetro en `true`, porque antes en esta posición se mandaba el param `$test` y ahora se manda `$features`

2024-01-19 15:48 UTC, jlmobbex approved these changes

2024-01-19 15:48 UTC, merged