[ECO-649] Changes Mobbex Tables charset to utf8mb4
mobbexco/php-plugins-sdk pull request #23
Opened 2023-11-08 17:18 UTC by EMunozMobbex

2023-11-09 15:26 UTC, jlmobbex requested changes

2023-11-09 15:26 UTC, jlmobbex commented on src/Model/Table.php
> +            if($data['Type'] !== 'text')
Se debería actualizar todas las columnas que contengan texto. Como está ahora quedarían afuera los `varchar`, `mediumtext`, `largetext`, etc. Una forma de chequear esto de forma simple es verificar que `Collation` no esté vacío.

2023-11-22 11:57 UTC, mobbexLuis approved these changes

2023-12-14 02:52 UTC, jlmobbex approved these changes

2023-12-14 02:52 UTC, merged