[ECO-723] Added an identifier for better security in webhook token.
mobbexco/php-plugins-sdk pull request #29
Opened 2024-02-19 20:03 UTC by EMunozMobbex

2024-02-23 21:55 UTC, jlmobbex requested changes

2024-02-23 21:55 UTC, jlmobbex commented on src/Repository.php
> +    public static function validateToken($id, $token)
Tenemos que dar soporte a los checkouts y suscripciones que crearon sus tokens usando el método antiguo, para eso propongo dos formas de resolver:
- Crear un método `deprecatedValidateToken($token)`
- Hacer que este método pueda recibir el ID como nulo, en caso de recibirse así, sólo se chequea usando las credenciales

También hay que tener en cuenta que en cada plugin debe usar ambos métodos para chequear este dato por ahora, por lo menos dejemos una versión de adaptación. Para el caso de los plugins de suscripciones debe chequearse de ambas formas por al menos 12 meses.

2024-02-27 11:50 UTC, mobbexLuis approved these changes

2024-02-29 12:48 UTC, jlmobbex approved these changes

2024-03-19 12:44 UTC, merged