[ECO-882] Improved the return of the requests to mobbex api.
mobbexco/php-plugins-sdk pull request #32
Opened 2024-03-11 14:48 UTC by EMunozMobbex

2024-03-11 23:04 UTC, jlmobbex requested changes

2024-03-11 23:04 UTC, jlmobbex commented on src/Api.php
> +        return isset($result['data']) && !empty($result['data']) ? $result['data'] : $result['result'];
No creo que este sea el camino, dado que en todas las peticiones de obtención de datos se necesita saber que información exacta devuelve la API, aunque esté vacía. Por ejemplo, en la obtención de operaciones mediante reference, si se devuelve un array vacío significa que la request se hizo correctamente pero que no hay operaciones que coincidan con la búsqueda.

Por otro lado, si "result" es false, salta una excepción en la línea 81, así que siempre que no vaya al catch result será true. Esto se puede usar para las ejecuciones de períodos que devuelven data vacía.

2024-03-12 21:00 UTC, EMunozMobbex commented on src/Api.php
> +        return isset($result['data']) && !empty($result['data']) ? $result['data'] : $result['result'];
Entonces mejor cerramos la PR y metemos una comprobación estricta de false del lado del plugin :O

2024-03-12 22:05 UTC, jlmobbex commented on src/Api.php
> +        return isset($result['data']) && !empty($result['data']) ? $result['data'] : $result['result'];
Si, me parece lo mejor. El plugin debería interpretar como result `true` el hecho de que no salte una excepción

2024-03-12 22:06 UTC, jlmobbex commented
El plugin debería interpretar como result `true` el hecho de que no salte una excepción

2024-03-12 22:06 UTC, closed without merging