[ECO-911] Fixed table definition check.
mobbexco/php-plugins-sdk pull request #34
Opened 2024-04-04 15:07 UTC by EMunozMobbex

2024-04-04 20:42 UTC, jlmobbex requested changes

2024-04-04 20:42 UTC, jlmobbex commented on src/Model/Table.php
> +                    'debug',
Este log sería de tipo error

2024-04-04 20:42 UTC, jlmobbex commented on src/Model/Table.php
> +                \Mobbex\Platform::log('debug', 'Table > checkCharset | empty or wrong collation:', $data);
Este log sería de tipo error

2024-04-04 20:42 UTC, mobbexLuis approved these changes

2024-04-05 15:08 UTC, jlmobbex approved these changes

2024-04-05 15:08 UTC, merged