Add support to mobbex cache
mobbexco/php-plugins-sdk pull request #8
Opened 2023-04-06 16:46 UTC by EMunozMobbex

# Notas

* Añadido soporte para cargar modelos de Mobbex desde los plugins.
* Añadido soporte para guardado de cache desde la tabla mobbex_cache.

2023-04-10 15:05 UTC, jlmobbex requested changes

2023-04-10 15:05 UTC, jlmobbex commented on src/Model/AbstractCache.php
> +     * @var timestamp
El tipo de variable es `string` para las fechas. Por otro lado, la documentación de las propiedades es al revés, primero va el título y después el tipo. Sólo se pone de esta forma cuando se realiza en una sóla línea, ej. `
    /** @var string Stored date. **/`. Recorá también que se suele dejar un espacio entre las distintas etiquetas o bloques, por ejemplo, entre el título y `@var` habría que dejar una línea vacía

2023-04-11 14:21 UTC, EMunozMobbex commented on src/sql/mobbex_cache.sql
> +  `date` TIMESTAMP DEFAULT NOW()
funciona desde MariaDB 10.0.1 y desde MySQL 4 en adelante

2023-05-08 15:23 UTC, jlmobbex commented on src/Platform.php
> +    /** @var Mobbex\Model\AbstractCache */
Un detallito acá, quedó agregar la barra previa al modelo (porque sino el IDE lo entiende como `\Mobbex\Mobbex...`)

2023-05-08 15:26 UTC, jlmobbex commented on src/Repository.php
> +        $key = 'mobbex_sources_' . md5(\Mobbex\Platform::$settings['api_key'] . \Mobbex\Platform::$settings['access_token'] . ($total ?: '') . ($installments ? json_encode($installments) : ''));
Estaría muy bueno aislar esto, quizás llevandolo a algún método de la clase abstracta de cache. Siento que la generación de la clave tendría que verse más sencilla o estar automatizada para no tener este choclo cada vez que se quiere obtener el dato jeje

2023-05-08 15:27 UTC, jlmobbex commented on src/sql/mobbex_transaction.sql
> +CREATE TABLE `DB_PREFIX_mobbex_transaction` (
Este archivo quedó de más creo

2023-05-31 17:38 UTC, jlmobbex commented on src/Cache.php
> +        return $key . md5($hash);
Esto se puede achicar con un `implode()`. Haciendose eso podría quedar todo en una línea 😉

2023-05-31 17:38 UTC, jlmobbex commented on src/Cache.php
> +    public static function generateKey($key, $params = [])
Esto podría ser:
```php
    public static function generateKey($key, ...$params)
```
Con esto te asegurás que params siempre sea un array, sin importar si se manda mal en otro lado. Al mismo tiempo ahorra la necesidad de usar `[]` al pasar los params

2023-06-02 14:00 UTC, jlmobbex requested changes

2023-06-02 14:00 UTC, jlmobbex commented on src/Repository.php
> +        $key  = \Mobbex\Cache::generateKey('mobbex_sources_', [$total, json_encode($installments)]);
Acá hay que sacar el `[]`, porque ahora se pasan como params separados hay que usar `,` solamente

2023-06-08 05:58 UTC, jlmobbex approved these changes

2023-06-08 05:58 UTC, merged